### PR TITLE
Rename packages under Coincoin namespace

### PR DESCRIPTION
**Pull request by yordis**

### CODE REVIEW

**Comment by yordis** [comment]
@robinmonjo I dont know if this is worth or not but I just did it. I renamed everything to be under `Coincoin` namespace. We never know if we will have to use X package that will conflict with the project or not and also if you decide to move the packages outside of `Coincoin` umbrella and publish them to Hex it will be ready without any problem. Which could be a possibility.

What do you think?

**Comment by robinmonjo** [comment]
Thank you @yordis ! In the current state of the project, I don't see how things could be reused outside of the project. 
I do have some ideas to separate the P2P layer outside of the Blockchain package, and maybe make it available on hex. And why not move the blockchain package to hex later too when it's more mature.

**Comment by yordis** [comment]
@robinmonjo should I continue with this or no?

**Comment by yordis** [comment]
@robinmonjo the reason I suggest this is because it is really interesting to actually extract `blockchain` as a database out and P2P as a network library as well.

I want to create some database for audio tracks on the blockchain ❤️ 🎧

**Comment by robinmonjo** [comment]
Ok @yordis let's focus on extracting the Blockchain so it can be reused. Extracting P2P protocol seems less important for now. I opened an issue https://github.com/robinmonjo/coincoin/issues/27 waiting for your inputs 😊

**Pull request closed without merging**
